### ISSUE TITLE
openstreetmapgeocoder throws error instead of callback (error)

### ISSUE THREAD

**Issue by wespen** [nchaulet/node-geocoder#103]
Hi,

Im using  node-geocoder/lib/geocoder/openstreetmapgeocoder.js
line 108 has throw err; so instead of calling passed callback it throws an error.
If you dont want to crash the app you need to put geocoder.reverse() in try catch.
Defeats the purpose of callback.

Can you set it to call callback (err, null)

**Comment by nchaulet** [comment]
fixed in 2.20.2
