### ISSUE TITLE
geocoder-reverse south hemisphere

### ISSUE THREAD

**Issue by muxa** [nchaulet/node-geocoder#117]
There's an error if trying to reverse geocode a southern hemisphere coordinate like this: 
```geocoder-reverse -37.1387194 175.5419382```
getting:
```error: unknown option `-3'```

**Comment by nchaulet** [comment]
It's a know bug of commander.js the library used for the cli tools https://github.com/tj/commander.js/issues/61

Maybe I should switch to another library

**Comment by nchaulet** [comment]
You can use the double hyphen -- to end option parsing, it seems to be the good solution I am going to add an example in the README

`geocoder-reverse -- -37.1387194 175.5419382`

**Comment by nchaulet** [comment]
Can I close the issue ?
