### ISSUE TITLE
crash when reversing latlon with openstreetmap

### ISSUE THREAD

**Issue by larfadin** [nchaulet/node-geocoder#126]
Hi thanks for you lib it's very good but it crash sometimes.
I use it with openstreetmap to reverse coordinate.

    geocoder.reverse({
        lat:latitude,
        lon: longitude
      }, function(err, res) {
        // dosomething...
      });
It crash if I send coordinate of the middle of sea because it's not a country.

    /home/user/Documents/myproject/node_modules/node-geocoder/lib/geocoder/openstreetmapgeocoder.js:64
    var countryCode = result.address.country_code;
                                    ^

    TypeError: Cannot read property 'country_code' of undefined
    at OpenStreetMapGeocoder._formatResult (/home/user/Documents/myproject/node_modules/node-geocoder/lib/geocoder/openstreetmapgeocoder.js:64:37)
        at /home/user/Documents/myproject/node_modules/node-geocoder/lib/geocoder/openstreetmapgeocoder.js:120:38
        at IncomingMessage.<anonymous> (/home/user/Documents/myproject/node_modules/node-geocoder/lib/httpadapter/httpadapter.js:47:9)
        at emitNone (events.js:72:20)
        at IncomingMessage.emit (events.js:166:7)
        at endReadableNT (_stream_readable.js:893:12)
       at doNTCallback2 (node.js:429:9)
        at process._tickCallback (node.js:343:17)

You return this value instead of data:

    console.log(result);  // ligne 64
    { error: 'Unable to geocode' }

And I can't find the error ligne 120 sorry.

Hope you can fix it soon !

**Comment by nchaulet** [comment]
I am looking to this :) do you have a latitude and longitude to reproduce the bug ?

**Comment by larfadin** [comment]
try something like this:
Latitude: 47.798397 | Longitude: -9.30542

It's in the ocean

**Comment by nchaulet** [comment]
Do you think it's better to throw an error with unable to geocode, or return an empty array of results ?

**Comment by larfadin** [comment]
I think you should return null. But I'm not that experiment

**Comment by larfadin** [comment]
Throw error would be better, because people won't understand why the array is empty and we just have to catch it.
Look at other service too maybe you got the same problem

**Comment by nchaulet** [comment]
fixed in v3.0.2

**Comment by larfadin** [comment]
that was fast ! thanks !

**Comment by nchaulet** [comment]
sorry i do a typo i fix this now

**Comment by nchaulet** [comment]
it should be okay :)
