### ISSUE TITLE
Question: openCageConfidence

### ISSUE THREAD

**Issue by fentas** [nchaulet/node-geocoder#131]
I looked though the opencage provider code and got a little confused by:
```js
var openCageConfidence = {
    10: 0.9, // < .25km
    9: 0.8, // < .5km
    8: 0.8, // < 1km
    7: 0.7, // < 5km
    6: 0.6, // < 7.5km
    5: 0.6, // < 10km
    4: 0.5, // < 15km
    3: 0.4, // < 15km ~ should be 20km
    2: 0.4, // < 25km
    1: 0.3, // > 25km
    0: 0 // NA
  };
```
Is there a point to neglect the precision of confidence, or mistake?
Maybe should be
```js
var openCageConfidence = {
    10: 1, // < .25km
    9: 0.9, // < .5km
    8: 0.8, // < 1km
    7: 0.7, // < 5km
    6: 0.6, // < 7.5km
    5: 0.5, // < 10km
    4: 0.4, // < 15km
    3: 0.3, // < 20km
    2: 0.2, // < 25km
    1: 0.1, // > 25km
    0: 0 // NA
  };
```

**Comment by nchaulet** [comment]
Sorry I did not work on this part but if you think confidence could be improved please do a pull request

**Comment by mlucool** [comment]
I agree this code seems off, given http://geocoder.opencagedata.com/api.html#confidence . 
What do you think of getting rid of these maps or clarifying what they do?

**Comment by nchaulet** [comment]
Totally agree, we can remove these maps :+1:

**Comment by fentas** [comment]
I would not remove these mappings.
These give good inside how accurate the results are. Only the implementation is off as I described above.
E.g. if confidence is `1` then you can be certain that the given result is within 250 meters. As for `0.1` more then 25 kilometers.

**Comment by mlucool** [comment]
Where do the 0.1-1 come from? I would still include something to limit you to set the confidence indicated in the doc (1-10) and even include a mapping that codifies it's meaning:
```
var openCageConfidenceInKM = {
    10: 0.25
    9: 0.5,
    8: 1,
    7: 5,
    6: 7.5,
    5: 10,
    4: 15, 
    3: 20,
    2: 25,
    1: Number.POSITIVE_INFINITY,
    0: Number.NaN
  };
```

Other than that I don't see where these two maps come into play.

**Comment by fentas** [comment]
@mlucool Nice, I agree. :+1:
