### ISSUE TITLE
Hangs randomly

### ISSUE THREAD

**Issue by ir-fuel** [nchaulet/node-geocoder#139]
Hi

I am using this lib to geocode a whole bunch of addresses using google (with an API Key and I pay for extra requests). What happens is that at random times the call to the geocoder just hangs. It doesn't time out, it doesn't give an error. It just hangs forever. The problem is that it is not reproducible. It does not happen on a specific address, just after a certain amount of calls.

**Comment by nchaulet** [comment]
Could I have more info ? are you using the google geocoder ?  and what amount of calls are we talking ?

**Comment by ir-fuel** [comment]
I wish I could give you a lot more info. I think I'll get the sources and add logging in your code. Right now I am using it installed through npm.

Yes it's google. I added a counter in my app, I have a minimum delay of 0.2 seconds between requests, they all happen sequentially (so no hammering of lib or server). As we speak it hangs on my machine in request 1861.

**Comment by ir-fuel** [comment]
I added some logging in `googlegeocoder.js`.
It's running right now. I'll let you know where it hangs.

**Comment by ir-fuel** [comment]
It hangs again while processing request number 1026.

`this.httpAdapter.get(this._endpoint, params, function (err, result) {`

callback function is never called. It hangs in there.

I did some heap dumps and I noticed (but I am no expert on this matter) that there is a `TLSWRAP` object that uses 23MB of memory.

**Comment by nchaulet** [comment]
What version of node are you using ?

**Comment by ir-fuel** [comment]
v4.1.1

**Comment by ir-fuel** [comment]
I changed some code in `httpadapter.js`

```
  if(typeof options.timeout !== 'undefined') {
    request.setTimeout(options.timeout);
  }
  else {
    request.setTimeout(30000);
  }
```

Because I see no way of passing the request timeout through the provided geocoder api. I'll see if this helps in unblocking the situation.

**Comment by ir-fuel** [comment]
So far I had one 

```
Error HttpError: connect ETIMEDOUT
```

when running my script. I'll leave it running to see if it completely stalls again or not.

**Comment by nchaulet** [comment]
To pass the timeout options

```
var geocoder = require('node-geocoder')('google', 'https', {timeout: 3000})
```

**Comment by ir-fuel** [comment]
This seems to have solved the problem. Maybe mention this option somewhere in the readme?

**Comment by nchaulet** [comment]
Yeah I am going to do this :+1+

On Mon, Nov 30, 2015 at 4:00 PM, ir-fuel <notifications@github.com> wrote:

> This seems to have solved the problem. Maybe mention this option somewhere
> in the readme?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nchaulet/node-geocoder/issues/139#issuecomment-160760201>
> .
>



-- 
Nicolas Chaulet (*Développeur Web)*

*Contact :*

    tél : 07 62 16 39 38
    mail : n.chaulet@gmail.com
    twitter : @n_chaulet <https://twitter.com/n_chaulet>

**Comment by nchaulet** [comment]
Added to the readme. Can I close the issue ?

**Comment by ir-fuel** [comment]
sure.
