### ISSUE TITLE
ESRI / ArcGIS reverse Geocoder location parameters

### ISSUE THREAD

**Issue by plutobium** [nchaulet/node-geocoder#140]
Thank you for the nice library!
I have been using it with Google and it works well.

When using it with ESRI / ArcGIS, I think I found a bug in the reverse geocoder.

As seen here:
https://developers.arcgis.com/rest/geocode/api-reference/geocoding-reverse-geocode.htm
location is x,y so one should pass location as long,lat.

lib/geocoder/agolgeocoder.js
...
AGOLGeocoder.prototype.reverse = function(query, callback) {
    var lat = query.lat;
    var long = query.lon;

    var _this = this;

    var execute = function (lat,long,token,callback) {
        var params = {
            'token':token,
            'f':'pjson',
            'location' : long + ',' + lat,  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<
...

Cheers!

**Comment by nchaulet** [comment]
Thanks for using it, Do you have the time to submit a pull request to fix to the bug ?

**Comment by nchaulet** [comment]
Thanks for the issue. I fixed it
