### ISSUE TITLE
Google maps request throws "REQUEST ERROR"

### ISSUE THREAD

**Issue by RobbeR** [nchaulet/node-geocoder#150]
Hi,
Thanks for the great library! One little bug, when I trying to geocode address which contains weird slovenian character (ŽIROVNICA city), geocoder returns the following error message: [Error: Status is INVALID_REQUEST.] I think the problem is with "stringify" method, but I'm not sure.

EDITED: After deeper investigate I realized the problem is NOT the "Z with the hat" character. The real problem caused by this character in a hungarian street name: \u001a (the street name came from database). Google said this is a "SUBSTITUTE" character (http://www.fileformat.info/info/unicode/char/001a/index.htm). The stringify encode it successfully as "%1A", and then the request fails, so I guess this is not an URL-safe character.

**Comment by nchaulet** [comment]
Thanks for the issue :+1:

**Comment by nchaulet** [comment]
the problem seems to be on google geocoder API do you think it's possible to replace the \u001a character by another one ?

**Comment by RobbeR** [comment]
In my database, this character is ALWAYS the substitute of the hungarian "ő" or "Ő" character (http://www.fileformat.info/info/unicode/char/0151/index.htm), I think some kind of character encoding conversion went wrong. In my case I can change all of my SUB character to "ő" and it works fine, but I'm not sure this is good for everybody in the future. I think sometimes the hungarian "ű"/"Ű" character can cause bugs like this.
Maybe the best solution in your Geocoder script is the substitute all of these chars with whitespaces before encoding the URL.
