### ISSUE TITLE
Google Geocoding

### ISSUE THREAD

**Issue by vanotis** [nchaulet/node-geocoder#151]
Need to add supporting of channels to Google Geocoding
See https://developers.google.com/maps/premium/reports/usage-reports#channels

**Comment by nchaulet** [comment]
:+1: Could you send a pull request ?

**Comment by vanotis** [comment]
Please add me as a collaborator, I don't have permissions at the moment.

**Comment by nchaulet** [comment]
You can fork the projection and send a pull request

**Comment by vanotis** [comment]
Done

**Comment by vanotis** [comment]
Please could you update the package version (forgot to do it in pull-request)?

**Comment by nchaulet** [comment]
Just published v3.7.0
