### ISSUE TITLE
Add channel support

### ISSUE THREAD

**Issue by florianschwarz** [nchaulet/node-geocoder#153]
Add a parameter extra.channel

to support the channel Google Maps API parameter:

https://developers.google.com/maps/documentation/geocoding/get-api-key#premium-auth

**Comment by florianschwarz** [comment]
Sorry for opening the ticket - there is already a pull request open:

Google geocoding: Added supporting of channels #152

**Comment by nchaulet** [comment]
yes I just need to publish a new version tonight :)
