### ISSUE TITLE
Feature request: automatic rate limiting

### ISSUE THREAD

**Issue by dbkaplun** [nchaulet/node-geocoder#165]
Checking from JS itself would be useful to prevent server rate limiting. There are a few solutions for JS rate limiting, including:

* [jhurliman/node-rate-limiter](https://github.com/jhurliman/node-rate-limiter)
* [wunderflats/promise-rate-limit](https://github.com/wunderflats/promise-rate-limit)
* [dbkaplun/rate-limit-promise](https://github.com/dbkaplun/rate-limit-promise) (disclaimer: I wrote this one)

**Comment by nchaulet** [comment]
I think client side rate limit should not be part of this package, maybe we can have a higher level package for doing this or it's the responsibility to the developer using node-geocoder to implement client side rate limit.
