### ISSUE TITLE
Google geocoder not using most specific value for neighborhood.

### ISSUE THREAD

**Issue by brandondtb** [nchaulet/node-geocoder#166]
Example:

`            {
               "long_name" : "Midtown",
               "short_name" : "Midtown",
               "types" : [ "neighborhood", "political" ]
            },
            {
               "long_name" : "Manhattan",
               "short_name" : "Manhattan",
               "types" : [ "sublocality_level_1", "sublocality", "political" ]
            },`

The geocoder will select "Manhattan" as the value for neighborhood when the more specific candidate value "Midtown" is available.

**Comment by brandondtb** [comment]
#167

**Comment by nchaulet** [comment]
Should be fixed now.
