### ISSUE TITLE
mapquest fails

### ISSUE THREAD

**Issue by simllll** [nchaulet/node-geocoder#168]
TypeError: Cannot read property '0' of undefined<br at /home/vcap/app/node_modules/node-geocoder/lib/geocoder/mapquestgeocoder.js:103:37 at IncomingMessage.<anonymous> (/home/vcap/app/node_modules/node-geocoder/lib/httpadapter/httpadapter.js:64:9) at emitNone (events.js:72:20) at IncomingMessage.emit (events.js:166:7) at endReadableNT (_stream_readable.js:913:12) at nextTickCallbackWith2Args (node.js:442:9) at process._tickDomainCallback (node.js:397:17)

regards

**Comment by nchaulet** [comment]
Wich version of node-geocoder are you using ?

**Comment by simllll** [comment]
Latest Version! I found out that i got an invalid reaponse due to a rate limit exception. I guess it's just this case which triggers the error.

**Comment by nchaulet** [comment]
Ok I think we can do better error handling for this Rate limit exception. I am probably going to work on this next week.
