### ISSUE TITLE
Google Maps + Cache - interesting question

### ISSUE THREAD

**Issue by tomerb15** [nchaulet/node-geocoder#183]
Hey and thanks for the great Lib!

I have a feeling that google is doing some kind of caching based on the client that generates the API calls.

For example, if my server calls google's API with the address:
17 aStreet, aCity

And then calls the API again with the address:
1 aStreet

The API will guess the city based on previous queries from the same client.
Its just a feeling but if its true, can we turn it off? I don't want google to relay on previous queries.

Any help will be greatly appreciated.

**Comment by nchaulet** [comment]
I do not think google API is doing cache, but I know google biases results in function of your location I think you can override this by using the  `region` option https://developers.google.com/maps/documentation/geocoding/intro?hl=fr#RegionCodes
