### ISSUE TITLE
Doesn't work on the client side

### ISSUE THREAD

**Issue by halt-hammerzeit** [nchaulet/node-geocoder#187]
Your library uses Node.js's `net` module
https://github.com/nchaulet/node-geocoder/blob/5c87789b1e916c99b9242d29fe1ba7b132ce6f2a/lib/geocoder/abstractgeocoder.js
And therefore it doesn't work on the client side.
Are you planning on porting it from `net` to something else, like `superagent`?

**Comment by halt-hammerzeit** [comment]
I took a look at your source code and seems that it only uses `net` for `.isIP()` stuff.
That's not the way to do it.
The proper way is to replace `net` with something like `ip` package:
https://www.npmjs.com/package/ip
Are you willing to do that yourself or is a Pull Request required?

**Comment by halt-hammerzeit** [comment]
There are also other modules like `crypto`, `util`, `url` – all that should be refactored in favour of none Node.js-specific stuff.

**Comment by halt-hammerzeit** [comment]
As a second thought, in my case it will be suitable to keep this on the server side only because of api keys. still, for "freeXXX" stuff it makes sense to be usable on the client

**Comment by nchaulet** [comment]
In my opinion, this library is not designed to be isomorphic and work on the client side.

**Comment by halt-hammerzeit** [comment]
Ok
