### ISSUE TITLE
geocoderfactory

### ISSUE THREAD

**Issue by Hugolboss** [nchaulet/node-geocoder#189]
node_modules/node-geocoder/lib/geocoderfactory.js:182
      httpAdapter = this._getHttpAdapter(httpAdapter, extra);
I am getting this error when i try to run this library any thoughts. If not I have fixed it locally but wondering if its something folks have seen it before.

**Comment by nchaulet** [comment]
Can I have more details on how you instantiate the geocoder ? and wich version are you using ?

**Comment by davidlsanborn** [comment]
I am working with Hugo.  We are using node-geocoder v3.14.0.  Here is how we instantiate it:

var NodeGeocoder = require('node-geocoder');
var options = {
  provider: 'google',
  httpAdapter: 'https', // Default
  apiKey: config.googleMaps.apiKey, // for Mapquest, OpenCage, Google Premier
  formatter: null         // 'gpx', 'string', ...
};
var geocoder_client = new NodeGeocoder(options);

**Comment by Hugolboss** [comment]
Node version v6.3.1 fyi

**Comment by nchaulet** [comment]
You are using `new NodeGeocoder`  the node-geocoder module is a factory and instantite the right classes for you (as mentionned in the doc) you should just do `var geocoder_client = NodeGeocoder(options);`

**Comment by nchaulet** [comment]
Can you confirm me it's working ?

**Comment by Hugolboss** [comment]
Will give it a go Now

**Comment by Hugolboss** [comment]
Its working , but now lint is complaining about our code   line 10  col 23  Missing 'new' prefix when invoking a constructor, but we can deal with that. Thank you so much for your help.

**Comment by nchaulet** [comment]
👍

**Comment by Hugolboss** [comment]
Epic Response time!
