### ISSUE TITLE
return the original response from google geocoder

### ISSUE THREAD

**Issue by michaelyao** [nchaulet/node-geocoder#19]
First, I want say "Thank You!". This is really nice piece of work!

This is more like a favorite or enhancement. If you can return the original response from google, or other provider, that will be very nice. Lots of time, we need know how "confident" google feel about the result, then we need look at the "partial match" flag in the original result.

One way is to just attach the original response as a node under current returned result.

Thanks

Michael

**Comment by jdelibas** [comment]
+1 @mendrik I was just about to suggest something along these lines.

I'm testing random UK postcodes, full and partial, against the original query response and seeing that ```postal_town``` could be used for ```locality``` and ```administrative_area_level_2``` for ```state```.

But this is still trial and error for my specific use case and I'm sure there are more gaps and potential problems it could cause for other countries.

https://developers.google.com/maps/documentation/geocoding/#Types

The detailed descriptions of each type are listed in the official docs.

For the geocoder to be clever enough I think it would need to know what country it is dealing with and match the parser would match the types based on that.
The scope of this would be quite large and prone to a fair few errors until every edge case is found.

An actual solution might be to do exactly as @michaelyao suggests and return the original response.

Parse the results as they are now and return a sub object with all the ```types``` and their corresponding values the parser didn't check for and this could be an optional trigger?

Or an optional custom parser?

I understand this might increase usage complexity but it would be an advanced optional feature.

**Comment by pbihler** [comment]
The simplest solution would be, to add a third argument to the callback (see PR #87 for implementation).
Existing code would simply ignore it, and in your special use cases, you can take and parse it yourself.

* Advantages:
  * Transparent for standard use-case
  * No polution of the unified data-result object

* Disadvantages:
  * Not translateable to the promise return. (So if you want to use rawData with promises, you have to wrap the callback manually).

Since it is a very special use case, I think the disadvantage is not a problem.

**Comment by pbihler** [comment]
Since the callback is called before resolving the promise, you can grab the rawData before `then`is called: 

```javascript
    var rawData = undefined
    geocoder.reverse(lat, long, function (err,data,raw) {rawData = raw})
      .then(function() {
        console.log(rawData);
      }, function(err) {
        console.error(err.message);
        process.exit(1);
      });
```

Or you can do a hacked kind of preprocessing in the callback: (works, because data is an array):

```javascript
geocoder.reverse(lat, long, function (err,data,raw) {data.length = 0; data.push(raw);})
      .then(function(result) {
        console.log(result[0]); // result[0] is the raw data
      }, function(err) {
        console.error(err.message);
        process.exit(1);
      });
```

**Comment by pbihler** [comment]
Alternative Implementation : PR #88 - The data result array ahs an additional property `raw`, so it is available in Promises (except for the error case, but we could easily attach the raw data to the error object as well...)

**Comment by skotchio** [comment]
I think it could be better to add posibility to override result formatter here https://github.com/nchaulet/node-geocoder/blob/master/lib/geocoder/googlegeocoder.js#L79

**Comment by nchaulet** [comment]
In node geocoder 2.8.1 raw response is available under the results raw property, thanks @pbihler  for your works.
Here is an example :

```javascript
geocoder.geocode('123').then(function(results) { console.log(results.raw); });
```
