### ISSUE TITLE
HTTP proxy support

### ISSUE THREAD

**Issue by jfgigand** [nchaulet/node-geocoder#190]
Hi,

I am using this module behind an HTTP proxy. How would you advise supporting this?

I am going to use module https-proxy-agent and pass an instance of it as the "agent" option to the lib/httpadapter/httpadapter.js.
However, a complete proxy support would use environment variables "http_proxy", "https_proxy" and "no_proxy". In other projects I use NPM module "request" which support this.

Thank you for the great work!
JFG

**Comment by nchaulet** [comment]
I am working on using request on a next version on node-geocoder. So the environment variables will be supported.

**Comment by nchaulet** [comment]
v3.15.0 now supports  request as an http adapter

```
var geocoder = require('./index')({
  provider: 'google',
  httpAdapter: 'request'
});
```

Can I close this issue ?

**Comment by jfgigand** [comment]
Yes, you can. This is a perfect solution. Thank you!
