### ISSUE TITLE
TypeError: net.isIPv4 is not a function

### ISSUE THREAD

**Issue by ibc** [nchaulet/node-geocoder#192]
I'm trying to get geolocation data given my public IP (or if possible, given nothing). I've tried to follow the code in `test/`:

```js
var geocoder = geocode({ provider: 'datasciencetoolkit' });
// or
var geocoder = geocode({ provider: 'freegeoip' });

var promise = geocoder.geocode('9.9.9.9');
```

and get:

```
Unhandled rejection TypeError: net.isIPv4 is not a function
at DataScienceToolkitGeocoder.AbstractGeocoder.geocode
```

The failing code is:

```js
if (net.isIPv4(value) && (!this.supportIPv4 || this.supportIPv4 == 'undefined')) {
  throw new ValueError(this.constructor.name + ' does not support geocoding IPv4');
}
```

Obviously, if `net.isIPv4` is not a function, we have a problem...

Do I miss something?

**Comment by ibc** [comment]
OK, `net` is loaded via `var net = require('net');`. This seems to work in Node, but when in cliend side + browserify, the Object returned by `require('net')` is an empty Object...

**Comment by ibc** [comment]
NOTE: Yes, I'm trying to use this module in the browser with browserify. I've realized now that this module is not supposed to work on the browser (or it may, but it's not guaranteed). So, if so, just close the issue, please.

**Comment by MikleSmart** [comment]
So, how did you resolve this problem?

**Comment by ibc** [comment]
BTW, this works in the browser as follows: https://github.com/ibc/node-geocoder/commit/6f56127b460375930d25573b5d8003d41559e1c5

**Comment by Leden4ik** [comment]
т.е. посчитали проблему закрытой. Хотя очевидно что проблема продолжается. Исправьте

**Comment by fgenoese** [comment]
Why was this fix never included in the main branch? I confirm it works with the current version.
