### ISSUE TITLE
Using NodeGeocoder with RxJs

### ISSUE THREAD

**Issue by danielocampo2** [nchaulet/node-geocoder#198]
Hi, first of all thanks for the library, it's quite cool.

I am now trying to bind the geocode callback with RxJs, but I can't seem to make it work.
The error that I get is the beloved '**TypeError: Cannot call method 'geocode' of undefined**'
The library without Rx is working fine, and I am also using Rx to run similar methods in other dependencies, as illustrated, and they also work just fine.
This code runs well until I try to geocode inside the Rx chain.

This is my simple code snippet:

```
var NodeGeocoder = require('node-geocoder')
var otherDependencie = require('other')

var options = { 
    // My Google API setup 
};
var geocoder = NodeGeocoder(options)

var executeRx = rx.Observable.fromNodeCallback(otherDependencie.execute)
var geocodeRx = rx.Observable.fromNodeCallback(geocoder.geocode)

executeRx("query")
    .flatMap(function (res) {
        return rx.Observable.fromArray(res)
    })
    .flatMap(function (item) {
        return geocodeRx(item.address)
    })
// And so on...
```

The only difference that I find between the functions I am calling is that execute is declared inside module.exports, while in this library prototype is being used.

I am new to Rx in Javascript (used it just in Java) and there seems not to be much documentation about this fromNodeCallback method (the given example is really simple):
I know that it also receives context as a parameter, so it might be lacking that, but everything I tried didn't work.
This is the Readme file of it: https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/fromnodecallback.md

Any help is highly appreciated, hope I am not the first one integrating Rx with this library.

Thanks!

**Comment by danielocampo2** [comment]
Hey, finally managed to do it by wrapping the function myself like this:

```
var geocodeRx = rx.Observable.fromNodeCallback(geocode)

function geocode(geocoder, address, callback){
    geocoder.geocode(address, function (err, res) {
        callback(err, res)
    })
}
```

Not sure if there is a better way that uses directly the NodeGeocoder, but I don't see much difference.

I will close it as it is solved to me, and there it is the 'solution' if anybody else needs it.

**Comment by nchaulet** [comment]
Hi thanks for the solution 👍 I am in a near futur going to add more doc and sample
