### ISSUE TITLE
dependenciesModule not found

### ISSUE THREAD

**Issue by ihsansatriawan** [nchaulet/node-geocoder#199]
Hi

i have tried use your package, but i got this :
```
ERROR in ./~/node-geocoder/lib/geocoder/agolgeocoder.js
Module not found: Error: Cannot resolve module 'net' in /home/hijup/site/Hijup_site/mobile/node_modules/node-geocoder/lib/geocoder
 @ ./~/node-geocoder/lib/geocoder/agolgeocoder.js 3:10-24
```

i have install with `npm install node-geocoder`

```
node -v    
v6.3.1

npm -v
3.10.3
```

similar this https://github.com/request/request/issues/1529, but still it's not working for me

**Comment by nchaulet** [comment]
are you trying to use node-geocoder client side ?
