### ISSUE TITLE
Support all reverse geocoding options for Google

### ISSUE THREAD

**Issue by yktv4** [nchaulet/node-geocoder#205]
aside of required params `lat` and `lon` the library only supports `language` optional param and `region` param (which I can't find in the maps api documentation). we still have `result_type` and `location_type` to pass.

you can find the full list of possible options here: https://developers.google.com/maps/documentation/geocoding/intro#ReverseGeocoding

**Comment by yktv4** [comment]
PR https://github.com/nchaulet/node-geocoder/pull/206

**Comment by nchaulet** [comment]
just published v3.16.0 with updates
