### ISSUE TITLE
batchGeocode for locationiq

### ISSUE THREAD

**Issue by nomoney4me** [nchaulet/node-geocoder#212]
I got an error when trying to use batchGeocode with the following code:

> /proj/addresscheck/node_modules/node-geocoder/lib/geocoder/locationiqgeocoder.js:73
>       var results = responseData.map(this._formatResult).filter(function(result) {
>                                  ^
> 
> TypeError: responseData.map is not a function
>     at LocationIQGeocoder.<anonymous> (/proj/addresscheck/node_modules/node-geocoder/lib/geocoder/locationiqgeocoder.js:73:34)
>     at IncomingMessage.<anonymous> (/proj/addresscheck/node_modules/node-geocoder/lib/httpadapter/httpadapter.js:62:9)
>     at emitNone (events.js:91:20)
>     at IncomingMessage.emit (events.js:186:7)
>     at endReadableNT (_stream_readable.js:974:12)
>     at _combinedTickCallback (internal/process/next_tick.js:74:11)
>     at process._tickCallback (internal/process/next_tick.js:98:9)

`var NodeGeocoder = require('node-geocoder');`
`var key = '';`
`var geocoder = NodeGeocoder({`
	`provider:'locationiq',`
	`apiKey:key,`
	`httpAdapter:'https',`
	`formatter:null`
`});`
`var addresses = [`
	`'1600 Pennsylvania Ave NW, Washington',`
	`'Washington, DC 22202'`
`]`
`geocoder.batchGeocode(addresses, function (err, results) {`
  `console.log(results) ;`
`});`

Is anyone else getting this error?

**Comment by Ephigenia** [comment]
I’ve been testing the code you’ve posted with node 7.7.3 and node 6.9.4 on OS X and it works.

**Comment by jberall** [comment]
I get no response as well.  Using Windows 10.
Response below.
[ { error: null, value: [ [Object] ] },
  { error: null, value: [ [Object] ] } ]

**Comment by nchaulet** [comment]
what do you have inside the property value?

**Comment by jberall** [comment]
I tried a variety of address
When the batch is submitted to google is it sent as a batch or individually?

Thanks,

var addresses = [
{address: '2485 Cornwall Ave Unit 10', city: 'Vancouver', stateCode: 'BC',
countryCode: 'CA', zipcode: 'V6k1b9'},
// 'Washington, DC 22202'
];
addresses = [
'1600 Pennsylvania Ave NW, Washington',
'Washington, DC 22202'
];

**Comment by jberall** [comment]
I tried a variety of address
When the batch is submitted to google is it sent as a batch or individually?

Thanks,

var addresses = [
    {address: '2485 Cornwall Ave Unit 10', city: 'Vancouver', stateCode: 'BC', countryCode: 'CA', zipcode: 'V6k1b9'},
    // 'Washington, DC 22202'
    ];
    
   addresses = [
      '1600 Pennsylvania Ave NW, Washington',
      'Washington, DC 22202'
      ];

**Comment by Ephigenia** [comment]
I’ve followed you’re provided code snippet and example `addresses` input for `batchGeocode`. Unfortunatly it resulted in exact the same `results` object as you provided. There was no TypeError thrown and the `results` objects contains the resolved geolocation response from locationiq which you also get. Please note that your [comment](https://github.com/nchaulet/node-geocoder/issues/212#issuecomment-325205557) contains objects in the `value` keys of the response.

> When the batch is submitted to google is it sent as a batch or individually?

Request is actually submitted to locationiq, not google …

If you’re not getting the TypeError which was the initally reason for this issue then this might be a differnt problem. 

The intial issue should be solved with the check if `responseData` has a length or not. Maybe @nchaulet should consider closing this issue.

**Comment by nchaulet** [comment]
Thanks I am closing the issue for now.

**Comment by jberall** [comment]
Thanks for the prompt help.


Jonathan Berall
