### ISSUE TITLE
does not work client-side

### ISSUE THREAD

**Issue by vincejah** [nchaulet/node-geocoder#217]
I am trying to make it work at client side, but this does not work because of querystring dependency:
```
Unable to resolve module `querystring`...
```

I've tried to add `querystring` as a project dependency but it does not work either. Do you have suggestions to make it work at client side?

**Comment by nchaulet** [comment]
This library is not designed to be isomorphic and it's not something going to change in the short term https://github.com/nchaulet/node-geocoder/issues/187
