### ISSUE TITLE
Rejection promis not handled

### ISSUE THREAD

**Issue by R0binT** [nchaulet/node-geocoder#224]
with the new version of nodejs, the module doesn't work anymore

`[DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I checked the code, and all promise are directly 
`return BP.resolve()`

no rejection handled

**Comment by nchaulet** [comment]
could you add more information wich geocoder are you using ? any example to have a repro
