### ISSUE TITLE
Google Geocoder ignoring postal_code component when country is not null

### ISSUE THREAD

**Issue by lgrosales** [nchaulet/node-geocoder#238]
Found an issue in the GoogleGeocoder when the country is null.

https://github.com/nchaulet/node-geocoder/blob/master/lib/geocoder/googlegeocoder.js#L43

Components is initialised as a null, so if the country is not provided the end result of the components section looks like: 

components=nullpostal_code:{postalCode}

This is causing Google to ignore the postal code and returning inaccurate results.

This is fixed by initialising the components as an empty string.

Please let me know if you agree with the change and I'll submit a PR.

Thanks,
leo

**Comment by nchaulet** [comment]
Fixed in v3.21.1 Thanks for the PR.
