### ISSUE TITLE
Discussion: Cache responses

### ISSUE THREAD

**Issue by blakek** [nchaulet/node-geocoder#240]
Would caching results be positively received if added?  If so, I'd like to work on a PR for this.

My idea for implementation of the cache would be similar to that of [dataloader](https://www.npmjs.com/package/dataloader#new-dataloaderbatchloadfn--options).  There would be a `cache` option added to the options object that would accept any object with an API similar to [`Map`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map).

According to the [Google Maps ToS](https://developers.google.com/maps/terms#section_10_5), the cache cannot persist for more than 30 days.  Caching is acceptable if used "for the purpose of improving the performance...due to network latency".  Because of the 30 day limitation—and because many would probably be interested in caching for fewer days—I'm thinking the options would also have a `cacheTimeout` option.  `cacheTimeout`'s value would be a Number representing the number of milliseconds from the time of caching that the entry would be considered stale and a network request would happen.

Thanks in advance!

**Comment by nchaulet** [comment]
Thanks to open the discussion on this subject.

I am not sure about implementing the cache inside the library, but I think it could be nice to have an F.A.Q or explain in the readme, how you can implement cache for node-geocoder.

Let me know your opinions on that.

**Comment by blakek** [comment]
I hadn't thought about that.  Adding an example to the readme would certainly be simpler.  I can make a PR if you're interested.  Maybe a small example under the "More" section?

**Comment by nchaulet** [comment]
Yes Looks a good idea maybe 👍
