### ISSUE TITLE
Snyk Security

### ISSUE THREAD

**Issue by knoxcard** [nchaulet/node-geocoder#257]
? ✗ Medium severity vuln found in cryptiles@3.1.2, introduced via node-geocoder@3.22.0
    Description: Insecure Randomness
    Info: https://snyk.io/vuln/npm:cryptiles:20180710
    From: node-geocoder@3.22.0 > request-promise@4.2.2 > request@2.86.0 > hawk@6.0.2 > cryptiles@3.1.2

**Comment by nchaulet** [comment]
Going to upgrade 👍

**Comment by nchaulet** [comment]
Upgraded
