### ISSUE TITLE
Documentation: OSM links outdated

### ISSUE THREAD

**Issue by DanielSWolf** [nchaulet/node-geocoder#274]
The links in the README regarding OSM are outdated. You might want to use these instead:

* Geocoding parameters: <http://nominatim.org/release-docs/latest/api/Search/>
* Reverse-geocoding parameters: <http://nominatim.org/release-docs/latest/api/Reverse/>
* Usage policy: <https://operations.osmfoundation.org/policies/nominatim/>
* Local installation: <http://nominatim.org/release-docs/latest/admin/Installation/>

**Comment by nchaulet** [comment]
Thanks I am going to update 👍
