### ISSUE TITLE
Is there a Working Adonis Service Provider for This Package?

### ISSUE THREAD

**Issue by PatrickLumenus** [nchaulet/node-geocoder#277]
I found an Adonis-Geocoder that wraps this package up for easier use with AdonisJS. But, it seems it is no longer supported. Well, its README is outdated and it has not been updated in over 2 years. 

I was wondering if there was a more recently supported one? If not, that's fine. I'll just use this package. :)

**Comment by nchaulet** [comment]
Hi @PatrickLumenus I am not familiar about AdonisJS but I think to use directly this package instead of adonis-geocoder
