### ISSUE TITLE
HERE not working – changes in REST API authentication

### ISSUE THREAD

**Issue by jvolker** [nchaulet/node-geocoder#286]
HERE REST API is no longer generating app codes for authentication. It now only generates API-keys. `node-geocoder`, on the other hand, throws an error ("You must specify appId and appCode to use Here Geocoder") if `appId` and `appCode` are not specified for HERE and `apiKey` is used instead. 

Previously generated`app_id` and `app_code` for authentification still seem to work. Therefore, `node-geocoder` can't be used with HERE if you didn't generate the credentials in the past. 

https://developer.here.com/documentation/authentication/dev_guide/topics/api-key-credentials.html

**Comment by dotupNET** [comment]
This is a working version:
https://github.com/nchaulet/node-geocoder/pull/291

**Comment by nchaulet** [comment]
Resolved by #302
