### ISSUE TITLE
Yandex: wrong parameter name is used

### ISSUE THREAD

**Issue by Hellwest** [nchaulet/node-geocoder#288]
At https://github.com/nchaulet/node-geocoder/blob/957dfc6aad087044097e430db0d816df9c8a9a69/lib/geocoder/yandexgeocoder.js#L75~L86

Parameter kind is used instead of bbox in the second IF statement

https://tech.yandex.com/maps/geocoder/doc/desc/concepts/input_params-docpage/

My pull request: https://github.com/nchaulet/node-geocoder/pull/289

**Comment by Hellwest** [comment]
@nchaulet please deploy the fix to NPM

**Comment by nchaulet** [comment]
it's deployed
