### ISSUE TITLE
Metro Bundler error when resolving modules inside node-geocoder

### ISSUE THREAD

**Issue by ziyaddin** [nchaulet/node-geocoder#292]
```
error: bundling failed: Error: Unable to resolve module `util` from
`node_modules/node-geocoder/lib/httpadapter/httpsadapter.js`: util could not
be found within the project.
```

This error applies to other modules such as `querystring`, `https`, `url` too.

**Comment by nchaulet** [comment]
Hi @ziyaddin 
This module is mean to run with node, if you want a geocoder for react native you should probably look for another module.
