### ISSUE TITLE
Issue since this morning

### ISSUE THREAD

**Issue by anthonycluse** [nchaulet/node-geocoder#300]
Hello,

Since this morning I get an issue with "node-geocoder".

I'm using Ubuntu to run my NodeJS app. It works on my local server and not on my remote server (Ubuntu).

`/var/www/****/****.fr.3015/cms/node_modules/node-geocoder/lib/httpadapter/fetchadapter.js:11
    this.options = { ...options };
                     ^^^
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/****/*****.fr.3015/cms/node_modules/node-geocoder/lib/geocoderfactory.js:9:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/****/****.fr.3015/cms/node_modules/node-geocoder/index.js:3:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)`

**Comment by nchaulet** [comment]
Hi @anthonycluse  what version of `node` and `node-geocoder` are you running?

**Comment by anthonycluse** [comment]
My version :
****:~$ node -v
v6.9.4
****:~$ npm -v
3.10.10
icecom@web-prod:~$

**Comment by nchaulet** [comment]
You can use an older version of node-geocoder like 3.23.0 that should work, also you should consider upgrading node

**Comment by anthonycluse** [comment]
I've updated my previous post with my versions.

**Comment by nchaulet** [comment]
My previous answer is still valid

**Comment by anthonycluse** [comment]
I tried to change my version of `node-geocoder` from 3.26.0 to 3.23.0 and I got the same issue 👍 

```
61|gestiaweb.fr.3015  | SyntaxError: Unexpected token ...
61|gestiaweb.fr.3015  |     at Object.exports.runInThisContext (vm.js:76:16)
61|gestiaweb.fr.3015  |     at Module._compile (module.js:542:28)
61|gestiaweb.fr.3015  |     at Object.Module._extensions..js (module.js:579:10)
61|gestiaweb.fr.3015  |     at Module.load (module.js:487:32)
61|gestiaweb.fr.3015  |     at tryModuleLoad (module.js:446:12)
61|gestiaweb.fr.3015  |     at Function.Module._load (module.js:438:3)
61|gestiaweb.fr.3015  |     at Function._load (/usr/local/lib/node_modules/pm2/node_modules/@pm2/io/build/main/src/metrics/transaction.js:109:33)
61|gestiaweb.fr.3015  |     at Module.require (module.js:497:17)
61|gestiaweb.fr.3015  |     at Module.newFunc (/usr/local/lib/node_modules/pm2/node_modules/deep-metrics/lib/aspect.js:101:26)
61|gestiaweb.fr.3015  |     at require (internal/module.js:20:19)
61|gestiaweb.fr.3015  |     at Object.<anonymous> (/var/www/gestiaweb/gestiaweb.fr.3015/cms/node_modules/node-geocoder/lib/geocoderfactory.js:9:22)
61|gestiaweb.fr.3015  |     at Module._compile (module.js:570:32)
61|gestiaweb.fr.3015  |     at Object.Module._extensions..js (module.js:579:10)
61|gestiaweb.fr.3015  |     at Module.load (module.js:487:32)
61|gestiaweb.fr.3015  |     at tryModuleLoad (module.js:446:12)
61|gestiaweb.fr.3015  |     at Function.Module._load (module.js:438:3)
61|gestiaweb.fr.3015  |     at Function._load (/usr/local/lib/node_modules/pm2/node_modules/@pm2/io/build/main/src/metrics/transaction.js:109:33)
61|gestiaweb.fr.3015  |     at Module.require (module.js:497:17)
61|gestiaweb.fr.3015  |     at Module.newFunc (/usr/local/lib/node_modules/pm2/node_modules/deep-metrics/lib/aspect.js:101:26)
61|gestiaweb.fr.3015  |     at require (internal/module.js:20:19)
61|gestiaweb.fr.3015  |     at Object.<anonymous> (/var/www/gestiaweb/gestiaweb.fr.3015/cms/node_modules/node-geocoder/index.js:3:23)
61|gestiaweb.fr.3015  |     at Module._compile (module.js:570:32)
```

**Comment by nchaulet** [comment]
Can you try an older version like 3.10

**Comment by anthonycluse** [comment]
Yes, indeed, it works forcing the version to "3.10.0". But i still need to understand why it was working yesterday on my remote server...

What's are working in `package.json` : 3.10.0
What's are not working in `package.json`  : ^3.10.0

**Comment by nchaulet** [comment]
Since 3.24.0 node-geocoder do not support node 6 anymore. I really encourage you to upgrade your node version

**Comment by anthonycluse** [comment]
Ok thank you.
