### ISSUE TITLE
🐛 Sometimes country name is returned as `United States of America` and sometimes `United States`

### ISSUE THREAD

**Issue by a-tokyo** [nchaulet/node-geocoder#336]
Unlike other geocoders, locationIQ uses the country name `United States of America` instead of `United States`.

Fix: https://github.com/nchaulet/node-geocoder/pull/335

**Comment by rocainunwired** [comment]
LocationIQ Team has fixed this issue internally and it now returns only `United States of America` as the country for US addresses

And the `display_name` value from the LocationIQ API response shall have `USA` for such addresses.

**Comment by rocainunwired** [comment]
LocationIQ team will factor this in during the next major API version release. Changes to the existing version is not possible at the API end as it might be a breaking factor for other users.

**Comment by A-Tokyo** [comment]
@rocainunwired Agreed 👍🏻 I handled the issue in our backend temporarily for now. 

**Should I close this issue or keep it open for reference for other people?**
