### ISSUE TITLE
is there a limit on the reverse?

### ISSUE THREAD

**Issue by ashwathps** [nchaulet/node-geocoder#46]
Hi,
Firstly, thanks for a superb module. Well done!

I am trying to use your package for reverse geocoding my coords. I am basically using it inside a " async.filter() " function to reverse geocode the coordinates.
What I observe is that, the  " geocoder.reverse " returns  " res = undefined and err = {} " for some valid coordinates. When i try reversing just this one separately from the node REPL, it returns correctly.

Code:

 async.filter(rws, function(row, cb){
                        if(!(row.lat && row.long)) { return cb(false); }
                        geocoder.reverse(row.lat, row.long, function(err, res){
                             if(!res) { return cb(false); }
                            if(err) { return cb(false); }
                        });
                 }, function(filteredresults){
                });

What could be the issue?

**Comment by realmike33** [comment]
What is the rate limit?

**Comment by nchaulet** [comment]
For the google provider 2500 req/day and 50 req/seconds
https://developers.google.com/maps/documentation/geocoding/usage-limits?hl=FR
