### ISSUE TITLE
geocoding crashes when OpenStreetMaps http://nominatim.openstreetmap.org/ is down

### ISSUE THREAD

**Issue by iamgoodbytes** [nchaulet/node-geocoder#59]
Earlier today, http://nominatim.openstreetmap.org/ was down and my app kept crashing. Is there a way to not crash when http://nominatim.openstreetmap.org/ is down?

Uncaught TypeError: Cannot read property 'country' of undefined

**Comment by pbihler** [comment]
You can wrap your call in try{}-catch ...

**Comment by iamgoodbytes** [comment]
Of course, sorry about that! Don't know why I didn't caught that.
