### ISSUE TITLE
Remove requestify requirement for ArcGIS use

### ISSUE THREAD

**Issue by spencerapplegate** [nchaulet/node-geocoder#68]
I could not get requestify working with ArcGIS. Using https as the httpAdapter should be sufficient. The Changelog specifies that the requestify httpAdapter was removed at 2.0, but it is required to use the ArcGIS provider

**Comment by nchaulet** [comment]
v2.13.1 should resolve the bug you can now use https adapter 

an example 

```
var geocoder = require('node-geocoder').getGeocoder('agol', 'https', {
    client_id: 'CLIENT ID',
    client_secret: 'SECRET'
});
```

**Comment by spencerapplegate** [comment]
thanks @nchaulet!
