### ISSUE TITLE
Geocoding intersections with `&` returns incorrect address

### ISSUE THREAD

**Issue by smswz** [nchaulet/node-geocoder#72]
For geocoding addresses that are intersections of two streets, the address is written as:
```Man O' War Blvd & Polo Club Blvd Lexington, Kentucky, 40509```

When sent through the library the `&` needs to be replaced with a URI encoded character `%26`, otherwise both Google and ArcGIS will return an incorrect address since it is getting parsed as a query parameter.

I'm not sure the best location where this replace would happen and for what adapters this would be necessary.

**Comment by nchaulet** [comment]
Fixed in v2.13.4, thanks for the issue :)
