### ISSUE TITLE
If 1 batch query fails, the whole batch fails

### ISSUE THREAD

**Issue by digitalsadhu** [nchaulet/node-geocoder#73]
When using the google adapter and the following set of data:

```
[ '19 Atuaroa Ave, Te Puke, New Zealand',
  '1235 ddetunf, no lamllf, New Zealand',
  '42 Puketapu Road , Taradale, Napier, New Zealand',
  'Pakuranga, Manukau, New Zealand',
  'flat 4/1broadfoot place, tekuiti, New Zealand',
  '25/15 Jickell St Hokowhitu , PalmerstonNorth, New Zealand',
  'Ruapehu Alpine Lifts Workshop Old Station Road, Ohakune, New Zealand',
  '20 Furlong Steert , Hawera 4610, New Zealand',
  '2 Rodney street, Levin, New Zealand',
  '31 Monro Street, Blenheim, New Zealand' ]
```

I get the following error:
```
[Error: Status is ZERO_RESULTS.]
```

When I ensure that the data is all valid addresses such as:
```
[ '19 Atuaroa Ave, Te Puke, New Zealand',
  '42 Puketapu Road , Taradale, Napier, New Zealand']
```

All is well.

Is this expected behaviour? Shouldn't it return all successful results rather than failing everything if one fails?

**Comment by nchaulet** [comment]
Is the expected behaviour, but maybe I must change that, I need to think about it

**Comment by digitalsadhu** [comment]
I tried the esri adapter with the same data and had no problems

**Comment by nchaulet** [comment]
it seems the adress: 1235 ddetunf, no lamllf, New Zealand could not be geocode by google

**Comment by nchaulet** [comment]
I am looking for a solution to return all successfull results and errors

**Comment by digitalsadhu** [comment]
nice

**Comment by nchaulet** [comment]
in node-geocoder 2.14.0 

batchGeocode return an array [{error: false, value: [...]}, {error: Error(), value:[]}],

**Comment by digitalsadhu** [comment]
:+1: nice one
