### ISSUE TITLE
opencage geocoder doesnt work for  49.0068901,8.403652700000066

### ISSUE THREAD

**Issue by Freundschaft** [nchaulet/node-geocoder#76]
for the latlng mentioned above, the geocoder for opencage doesnt give me the city. The city field is not returned also from direct API invocation at opencage, but the county is returned. Unfortunately there is no county represenatation within the node-geocoder library. So i'm stuck with having no city name there.

**Comment by nchaulet** [comment]
I am going to add county property

**Comment by Freundschaft** [comment]
thanks!

**Comment by nchaulet** [comment]
there is no a county property in v2.16.0 :)
