### ISSUE TITLE
Check for mistyped/invalid properties

### ISSUE THREAD

**Issue by gajus** [nchaulet/node-geocoder#78]
Neither `getGeocoder` (extra parameter) nor the `geocode` function of the resulting object validate the input option. It is easy to mistake "apiKey" with "apikey" or add a completely unsupported parameter. It should not fail silently when property is not recognised.

**Comment by chovy** [comment]
i'm getting something wrong, don't know what:

`Error: You must use https http adapter`

**Comment by nchaulet** [comment]
To avoid this error https is now the default adapter

**Comment by fahdsheikh** [comment]
Yeah I had this error, too. It was working fine with http, and then I had cloned down my project again and suddenly I got that message. I changed to https, but now reverse geocoding doesn't work. Any way I can revert to http? I don't see why this change happened so suddenly for me when it was working fine

**Comment by nchaulet** [comment]
Hi you google geocoder ? and are you using api key or not ?

**Comment by fahdsheikh** [comment]
Yesterday I used an api key with http, and yes I was using google geocder. Today, I got the same message but removed the extra two arguments and it works fine with no api key. 
```
geocoder = require('node-geocoder')('google')
```

instead of 

```
geocoder = require('node-geocoder')('google','http', extra)
```

although when i changed 'http' to 'https' in the latter, i get no location.

**Comment by nchaulet** [comment]
Can I see a reverse call ?

On Wed, Aug 26, 2015 at 3:34 PM, Fahd Sheikh <notifications@github.com>
wrote:

> Yesterday I used an api key with http, and yes I was using google geocder.
> Today, I got the same message but removed the extra two arguments and it
> works fine with no api key.
>
> geocoder = require('node-geocoder')('google')
>
> instead of
>
> geocoder = require('node-geocoder')('google','http', extra)
>
> although when i changed 'http' to 'https' in the latter, i get no location.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nchaulet/node-geocoder/issues/78#issuecomment-135022680>
> .
>



-- 
Nicolas Chaulet (*Développeur Web)*

*Contact :*

    tél : 07 62 16 39 38
    mail : n.chaulet@gmail.com
    twitter : @n_chaulet <https://twitter.com/n_chaulet>

**Comment by nchaulet** [comment]
I have released version 3.0 of node-geocoder and the deprecated call reverse(lat, lng) add be removed the good way to call reverse is now reverse({lat: *, lon: *})

**Comment by fahdsheikh** [comment]
this is what i was using for my api calls

```
router.post('/api/geocoder', function(req, res) {
  var latitude = req.body.latitude;
  var longitude = req.body.longitude;
  geocoder.reverse({
    lat: latitude,
    lon: longitude
  }, function(err, cityData) {
    if (err) {
      return res.json(500, err);
    } else {
      res.json(cityData);
    }
  });
});
```

**Comment by nchaulet** [comment]
and what error do you have ? are you using just an apiKey or Google Maps API for Work with a clientId ?

**Comment by fahdsheikh** [comment]
the error was only when i included an api key as part of the request for geocoder with https, resulting in no output..with no server apikey everything works fine now, so the error is gone on that part. I do have an api key for google maps in effect.

**Comment by nchaulet** [comment]
I was just testing this using an extra.apiKey and it work's fine

```javascript
Geocoder('google', 'https', extra).reverse({lat: '45.7492277',
    lon: '4.8386345'}, function(err, results) {
    console.log(results);
    console.log(err)
});

```

**Comment by nchaulet** [comment]
you still have the error ?
