### ISSUE TITLE
v 2.17.0 dont work with google geocode

### ISSUE THREAD

**Issue by bitgandtter** [nchaulet/node-geocoder#82]
I test this with the README example and i get non response, debug some more and in the googlegeocoder its returning the response, but some point in the middle get lost. I was forced to go back to 2.16.0

**Comment by nchaulet** [comment]
Sorry I made a typo it should be fixed in 2.17., thanks for your issue.

Can you confirm bug is fixed ?

**Comment by bitgandtter** [comment]
confirmed its fixed, thanks, great work

**Comment by gabrielpconceicao** [comment]
Yes, its fixed! Thanks!
