### ISSUE TITLE
Add Filelds

### ISSUE THREAD

**Issue by chiarishow** [nchaulet/node-geocoder#94]
Hi, 

can you please add the following fields:

'village' : result.address.village,
'hamlet' : result.address.hamlet,

in the ._formatResult function of nominatimmapquestgeocoder.js and openstreetmapgeocoder.js

Or you can simply modify:
 'city' : result.address.city || result.address.town with
'city' : result.address.city || result.address.town || result.address.village || result.address.hamlet.

This happened because sometimes, for example here in Italy, there are really small town classified like village or hamlet but in fact they are towns.

Thank you!

**Comment by nchaulet** [comment]
The 2nd solution seems nice, could you eventually made a pull request ?
