### ISSUE TITLE
Is it possible to use this module on client-side?

### ISSUE THREAD

**Issue by skotchio** [nchaulet/node-geocoder#98]
I've implemented `node-geocoder` on server-side and it works well. Now I need to get it client-side. Is it possible to adopt this module or there are some other modules for my task?

**Comment by nchaulet** [comment]
I think node-geocoder does not work on client side, you could try with browserify or webpack. For client side I used a long time ago geocoder.js https://github.com/geocoder-php/geocoder-js

**Comment by skotchio** [comment]
@nchaulet thanks for the reply. Bassicly I need format method that could ensure the following format:

// output :
    [{
      latitude: 48.8698679,
      longitude: 2.3072976,
      country: 'France',
      countryCode: 'FR',
      city: 'Paris',
      zipcode: '75008',
      streetName: 'Champs-Élysées',
      streetNumber: '29',
      state: 'Île de France',
      stateCode: 'IDF'
  }]

**Comment by skotchio** [comment]
Is it possible to port only formatter function on client-side?

**Comment by nchaulet** [comment]
You could easily create your own formatter on top of geocoder.js or other library

**Comment by skotchio** [comment]
@nchaulet could you answer why you decide to use exactly the following structure:

    [{
      latitude: 48.8698679,
      longitude: 2.3072976,
      country: 'France',
      countryCode: 'FR',
      city: 'Paris',
      zipcode: '75008',
       streetName: 'Champs-Élysées',
       streetNumber: '29',
       state: 'Île de France',
       stateCode: 'IDF'
    }]

**Comment by nchaulet** [comment]
I use an array because some geocoder return an array with many addresses

**Comment by skotchio** [comment]
Ok but what about fields and their names?

**Comment by nchaulet** [comment]
Wich fields do you misunderstand ?

**Comment by skotchio** [comment]
I mean all field names `latitude`, `longitude`, `countryCode` and etc. Do they inspired some framework or is completely your decision?

**Comment by nchaulet** [comment]
It is inspired by python geocoder https://github.com/DenisCarriere/geocoder and php geocoder https://github.com/geocoder-php/Geocoder

**Comment by skotchio** [comment]
Thanks for the answers and for your great work!
